# Generated by Django 5.2.15 on 2026-10-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0012_remove_complaint_is_ngo_assisted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='civicproject',
            name='csr_pledged_amount',
        ),
        migrations.RemoveField(
            model_name='civicproject',
            name='csr_sponsor_name',
        ),
        migrations.RemoveField(
            model_name='civicproject',
            name='is_csr_supported',
        ),
        migrations.RemoveField(
            model_name='civicproject',
            name='is_ngo_audited',
        ),
        migrations.RemoveField(
            model_name='civicproject',
            name='ngo_audit_remarks',
        ),
        migrations.RemoveField(
            model_name='civicproject',
            name='ngo_auditor_name',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='assisted_by_ngo_name',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='beneficiary_name',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='beneficiary_phone',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='is_assisted_filing',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='is_ngo_audited',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='ngo_audit_remarks',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='ngo_auditor_name',
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_ngo_assisted',
            field=models.BooleanField(default=False, help_text='Filed by registered NGO on behalf of rural citizen'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ngo_name',
            field=models.CharField(blank=True, help_text='Name of assisting NGO', max_length=150),
        ),
        migrations.AddField(
            model_name='complaint',
            name='rejection_image',
            field=models.ImageField(blank=True, help_text='Citizen photo proof showing issue remains unresolved', null=True, upload_to='complaints/rejections/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Citizen rejection feedback when officer resolution is disputed'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='rural_citizen_name',
            field=models.CharField(blank=True, help_text='Name of rural citizen beneficiary', max_length=150),
        ),
        migrations.AddField(
            model_name='complaint',
            name='rural_citizen_phone',
            field=models.CharField(blank=True, help_text='Mobile phone number of rural citizen beneficiary', max_length=15),
        ),
    ]
